### PR TITLE
Handle sidewalk=separate and none. Closes #249

### LINKED ISSUE #249: `sidewalk=separate` unsupported
Ways that have a `sidewalk=separate` tag lead to a conversion error.

`Conversion Error: unsupported: 'sidewalk=separate' - osm2lanes/src/transform/tags_to_lanes/modes/foot_shoulder.rs:213:32`

### PR DESCRIPTION
**Pull request by dabreegster**
This PR handles `sidewalk=separate` by silently ignoring it and not adding a sidewalk, because it's not the job of osm2lanes to figure out parallel ways. And it handles `sidewalk=none` by treating it the same as `no` and adding a deprecated warning.

### CODE REVIEW

File: osm2lanes/src/transform/tags_to_lanes/modes/foot_shoulder.rs [hunk 1]
```diff
@@ -38,7 +38,9 @@ impl LaneBuilder {
 }
 
 enum Sidewalk {
-    None,
+    /// No information. This variant isn't called `None`, because that could be confused with
+    /// `sidewalk=none`.
+    Unknown,
```
Comment (BudgieInWA) [inline osm2lanes/src/transform/tags_to_lanes/modes/foot_shoulder.rs:43]: I like this change.

**Review by BudgieInWA — APPROVED** [review]

File: osm2lanes/src/transform/tags_to_lanes/modes/foot_shoulder.rs (hunk 1 above)
Comment (dabreegster) [reply osm2lanes/src/transform/tags_to_lanes/modes/foot_shoulder.rs:43]: I was very confused for a good few minutes
